### PR TITLE
add grad for det, logdet and inv

### PR DESCRIPTION
**Pull request by CarloLucibello**
and also trace, diag, diagm, logabsdet, triu, tril
x-ref #45

### CODE REVIEW

**Comment by CarloLucibello** [comment]
merge?

**Comment by kirnap** [comment]
@CarloLucibello thanks for your efforts. I've just reviewed your implementations. Here are some issues I've discovered, do you have any solution or suggestion to solve these problems:
1. trace Implementation
```julia
		gradcheck(trace, rand(4,4)) # I am aware of that your test works
                 my_trace(x) = sum(trace(x)); my_trace(rand(4,4)) # works fine
		gradcheck(my_trace, rand(1,1)) # not working
```
2.logdet Implementation
```julia
		julia> t1
		4×4 Array{Float64,2}:
		0.81897   0.972307   0.59813   0.408066
		0.736922  0.451799   0.946951  0.141639
		0.127154  0.466463   0.271822  0.872671
		0.864788  0.0628381  0.205276  0.918354

		julia> logdet(t1)
		ERROR: DomainError:
		log will only return a complex result if called with a complex argument. Try log(complex(x)).
		Stacktrace:
		[1] nan_dom_err at ./math.jl:300 [inlined]
		[2] log at ./math.jl:419 [inlined]
		[3] logdet(::Array{Float64,2}) at ./linalg/generic.jl:1261

		julia> t2
		4×4 Array{Float64,2}:
		0.177807  0.518924  0.721952  0.305002
		0.244914  0.629782  0.704174  0.394654
		0.686861  0.486215  0.583889  0.902661
		0.756204  0.965346  0.766321  0.209436

	        julia> logdet(t2)
 	        -3.283823415533983

		julia> logdet(complex(t1))
       		-0.7562876304616563 - 3.141592653589793im
		# In case want to test by yourself the following line for a few times:
		julia> [ gradcheck(logdet, eye(3) + rand(3,3)) for i in 1:1000 ];
 ```
@denizyuret
1. For all other implementations we need  KnetArray Implementations.
2. In the logdet implementation issue we may face the following error:
```julia ERROR: MethodError: no method matching complex(::AutoGrad.Rec{Array{Float64,2}})```

**Comment by CarloLucibello** [comment]
I modified the logdet test to have it more unlikely to fail

**Comment by kirnap** [comment]
@CarloLucibello I saw your change,  other gradient checks are OK.

**Pull request merged**
