### PR TITLE
@gcheck added

### PR DESCRIPTION
**Pull request by ekinakyurek**
@gcheck with keyword arguments

### CODE REVIEW

**Comment by denizyuret** [comment]
I don't think this will work as proposed: gcheck function uses params(f), params(xarg), params(kwarg) to determine all the test targets. When you use a function with no arguments and is not a callable object no params will be checked. If for some reason I am mistaken and you tested this showing it to work let me know. Otherwise I will rewrite a version that iterates through the tape.

I like the macro keyword argument trick, is this a standard thing, or did you make this up?

**Comment by ekinakyurek** [comment]
After discussion,
@gcheck needs to figure out params in given expression
keyword argument handling, which proposed in this PR, for macro is okey.

**Comment by denizyuret** [comment]
I think I fixed it, can you check @ekinakyurek?

**Comment by denizyuret** [comment]
In the first case the input rand(5,5) is run every time. In the second case it is run once. If you put your input in a variable the difference disappears. This is expected behavior, i.e. gcheck evaluates all arguments before starting the check, @gcheck does not.

**Comment by ekinakyurek** [comment]
upps :) That is correct. We can merge it

**Pull request merged**
