### PR TITLE
remove <0.6 cruft

### PR DESCRIPTION
**Pull request by CarloLucibello**
should also run FemtoCleaner after this

### CODE REVIEW

**Comment by CarloLucibello** [comment]
weird, tests are failing on maco os. Is this usual?

**Comment by kirnap** [comment]
@CarloLucibello I had tested your this PR and nothing failed on mac-os? What did you mean by failing tests?

**Comment by CarloLucibello** [comment]
>@CarloLucibello I had tested this PR and nothing failed on mac-os? What did you mean by failing tests?

travis CI was failing on mac on the first try, but I guess it was an occasional failure not related to this PR

**Comment by denizyuret** [comment]
@CarloLucibello you removed bessel.jl, erf.jl, gamma.jl from AutoGrad.jl completely.  Was this on purpose?

**Comment by CarloLucibello** [comment]
> @CarloLucibello you removed bessel.jl, erf.jl, gamma.jl from AutoGrad.jl completely. Was this on purpose?

ops, that was a mistake, thanks for adding them back

**Comment by denizyuret** [comment]
no problem. thats what reviews are for ;)

**Pull request merged**
